directories:
  output: release
  buildResources: build
appId: com.example.myapp
productName: Casper
win:
  target: nsis
  icon: favicon.png
linux:
  category: Network
  icon: favicon.png
mac:
  category: Network
  icon: favicon.png
files:
  - filter:
      - index.js
      - favicon.png
extraFiles:
  - from: ./../../frontend/angular/dist/casper
    to: frontend/angular/dist/casper
<<<<<<< HEAD
electronVersion: 26.1.0
=======
electronVersion: 29.1.1
>>>>>>> e374407 (CI CD + tests + remove docs (#37))
