name: nightly-scheduled-test

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # runs every day at midnight
    - cron: '0 0 * * *'

jobs:
  nightly-make-test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    env:
      NODE_ADDRESS: http://127.0.0.1:7777/rpc
      EVENT_ADDRESS: http://127.0.0.1:9999/events/main
      # WARNING: These accounts, and their private keys, are publicly known.
      # Any funds sent to them on Mainnet or any other live network WILL BE LOST.
      SECRET_KEY_USER_1: MC4CAQAwBQYDK2VwBCIEII8ULlk1CJ12ZQ+bScjBt/IxMAZNggClWqK56D1/7CbI
      SECRET_KEY_USER_2: MC4CAQAwBQYDK2VwBCIEIJTD9IlUYzuMHbvAiFel/uqd6V7vUtUD19IEQlo6SAFC

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Audit
        uses: actions-rs/cargo@v1
        with:
          command: audit
          args: --deny warnings

      - name: Lint
        run: make check-lint

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@5b949b50c3461bbcd5a540b150c368278160234a #v3.4.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Casper node launcher js
        run: npx casper-node-launcher-js node --daemon

      - name: Unit Tests
        run: make test

      - name: Integration Tests
        run: make integration-test

      - name: E2E Tests
        run: make e2e-test

      - name: Build lib for all targets
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --lib --all-targets

      # - name: Slack Notification
      #   uses: ravsamhq/notify-slack-action@4ed28566c2bdcdaee6dca2b46b9666d01b4ed8a4 #v1.10.0
      #   if: always()
      #   with:
      #     status: ${{ job.status }}
      #     notification_title: '*{repo}*'
      #     message_format: '{emoji} *{workflow}* *{status_message}* in <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}>'
      #     footer: '<{run_url}|View Run>'
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Fake Commit after 50 days
        uses: gautamkrishnar/keepalive-workflow@790c7f09285a59b09bb578c85e271c6ff2af97c4 #v1.1.0
