name: Publish docs

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-deploy:
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Build packages and apps
        run: make build

      - name: Doc
        run: make doc

      - name: Github pages 🚀
        uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6 #v4.4.1
        with:
          folder: docs # The folder the action should deploy.
